/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WeirdDogApp;

public class App {
    public String getGreeting() {
        return "Obscure Dog Breeds in NYC";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

    }
}
